# Generated by Django 4.2 on 2023-04-28 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
                ('mobile_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('slug', models.SlugField(unique=True)),
                ('profession', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
