# Generated by Django 4.2 on 2023-05-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percent2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
