# Generated by Django 4.2 on 2023-05-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_skill_percent2_skill_skill2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
