# Generated by Django 4.2 on 2023-05-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_skill_percent2_alter_skill_skill2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='percent2',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill2',
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.userinfo'),
        ),
    ]
