# Generated by Django 4.2 on 2023-05-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_skill_percent2_remove_skill_skill2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='skill1',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percent',
        ),
        migrations.AddField(
            model_name='skill',
            name='percent1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='skill',
            name='percent2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
