# Generated by Django 4.2 on 2023-05-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_skill_skill_skill1_remove_skill_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percent2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
