# Generated by Django 4.2 on 2023-05-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_skill_percent2_skill_skill2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='percent2',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill2',
        ),
    ]
