# Generated by Django 4.2 on 2023-05-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_remove_skill_percent2_remove_skill_skill2'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percent2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
