# Generated by Django 4.2 on 2023-05-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_skill_percent2_skill_skill2'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percent3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='skill',
            name='percent4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='skill',
            name='percent5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
