# Generated by Django 4.2 on 2023-05-27 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0015_rename_percent1_skill_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_or_univ', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('school_or_college', models.CharField(max_length=300)),
                ('cgpa_or_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cgpa', models.BooleanField(default=False)),
                ('slug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.userinfo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
