# Generated by Django 4.2 on 2023-05-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='school_or_college',
        ),
    ]
