# Generated by Django 4.2 on 2023-05-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='post',
            new_name='role',
        ),
    ]
