# Generated by Django 4.2 on 2023-05-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_rename_post_experience_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='role',
            new_name='position',
        ),
    ]
