# Generated by Django 4.2 on 2023-06-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_alter_project_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
